{% set name = "pvextractor" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a54e986760cef6b186e02d1c3d98d7e1c18e4e75c5d0b71343b5ff59fd9c09c3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - astropy
    - matplotlib-base >=2.0
    - scipy
    - qtpy
    - spectral-cube

test:
  imports:
    - pvextractor
    - pvextractor.gui
    - pvextractor.geometry

about:
  home: https://github.com/radio-astro-tools/pvextractor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Position-velocity diagram extractor

extra:
  recipe-maintainers:
    - keflavich
    - astrofrog-conda-forge
